version: '3.4'

services:

  mssqldata:
    image: microsoft/mssql-server-linux:latest
    entrypoint: /bin/bash

  sqlserver:
    image: microsoft/mssql-server-linux:latest
    restart: always
    ports:
        - 1833:1433
    volumes:
      - /var/opt/mssql
      # we copy our scripts onto the container
      - ./sql:/usr/src/app 
    # bash will be executed from that path, our scripts folder
    working_dir: /usr/src/app 
    # run the entrypoint.sh that will import the data AND sqlserver
    command: sh -c ' chmod +x ./entrypoint.sh; ./entrypoint.sh & /opt/mssql/bin/sqlservr;'
    environment:
          - ACCEPT_EULA=Y
          - SA_PASSWORD=Password12!

  quoteapi:
    image: ${DOCKER_REGISTRY-}quoteapi
    build:
      context: .
      dockerfile: QuoteApi/Dockerfile
    depends_on: 
      - sqlserver